version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "myapiGateway"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-z40e66qg1izg"
s3_prefix = "myapiGateway"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

